# Generated by Django 4.1.5 on 2023-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_venue_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
